joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0

teleop_node:
  ros__parameters:
    axis_linear:
      x: 1
    # 0.69 is controller max
    scale_linear:
      x: 10.0
    scale_linear_turbo:
      x: 0.1

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 10.0
    scale_angular_turbo:
      yaw: 0.1

    enable_button: 1

    require_enable_button: true
